name: PHP Checks

on:
  push:

jobs:

  rex-lint:
    name: REX Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.1
        extension-csv: intl
        coverage: none # disable xdebug, pcov
    - run: |
        composer require --dev friendsofredaxo/linter && vendor/bin/rexlint
